name: podtato-head-monolith-tests

on:
  push:
    paths:
      - 'podtato-head-monolith/**'
  pull_request:
    paths:
      - 'podtato-head-monolith/**'

permissions:
  packages: write

env:
  CONTAINER_REGISTRY: ghcr.io
  GITHUB_TOKEN: ${{ github.token }}  
  GITHUB_USER: ${{ github.repository_owner }}
  
defaults:
  run:
    shell: bash

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build images
        run: ./podtato-head-monolith/build/build_image.sh
      - name: Test images
        run: ./podtato-head-monolith/build/test_image.sh
